### ISSUE TITLE
Exchange Class

### ISSUE THREAD

**Issue by luoc0815** [ppinard/pyxray#5]
@fingenerf wrote:
> With the pyXRAY module it is possible to get a lot of information about elements, their subshells and transitions. To use these information for example for a digital periodic table it would probably be a good idea to create some kind of an element exchange class to parse all the information about one specific element in one object. This class could not just be used for the periodic table, it could be used in other modules as well.

> This class would contain all the element information like the name, the weight and the density, all the information for each subshell of this element like the binding energy and radiative width and it would contain the information for each transition of this element like the transition 
energy.

What we're looking for is a exchange format for pyXRAY and applications of any kind. We would like to introduce a class on element level that collects all information about an element (or at least all information from one source).

@ppinard: What do you think about that idea? Do you already plan something similar?

**Comment by ppinard** [comment]
I am not quite sure what is the advantage of having a class with all these informations. Wouldn't it be better to only retrieve these informations when needed using the appropriate pyxray methods (e.g. `element_atomic_weight(...)`)? 

In any case, if you want to implement such class I don't see any disadvantage and it should be fairly straightforward using SQL queries. Have a look to the SQL command INNER JOIN.

Could you create the interface/skeleton of this class?

**Comment by luoc0815** [comment]
I agree, it's probably not worth the overhead in the moment but I'll keep this in mind for a later projects where we may use pyXRAY.
